name = "tel-pos"
main = "src/worker.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "tel-pos-db"
database_id = "e61d6d38-7574-433b-8226-7e8c9fbeea46"

[[durable_objects.bindings]]
name = "CALL_HUB"
class_name = "CallHub"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CallHub"]

[vars]
RESTAURANT_NAME = "EFE BÜFE"
RESTAURANT_ADDRESS = "Atatürk Mah. Cumhuriyet Cad. No:1"
RESTAURANT_PHONE = "0212 000 00 00"
